model-module: espnet.nets.pytorch_backend.e2e_lts_tacotron2:Tacotron2
width: 128
height: 64
elayers: 1
eunits: 512
econv-layers: 4
econv-chans: 24
econv-filts: 5
reduce-time-length: false
dlayers: 2
dunits: 1024
prenet-layers: 2
prenet-units: 256
postnet-layers: 5
postnet-chans: 512
postnet-filts: 5
use-speaker-embedding: true
atype: location
adim: 128
aconv-chans: 32
aconv-filts: 15
cumulate-att-w: true
use-batch-norm: true
use-concate: true
use-residual: true
use-masking: true
use-guided-attn-loss: true
bce-pos-weight: 1.0
reduction-factor: 2
batch-size: 16
batch-sort-key: output
maxlen-in: 150
maxlen-out: 400
lr: 1e-4
eps: 1e-6
weight-decay: 0.0
dropout-rate: 0.5
zoneout-rate: 0.1
epochs: 500
patience: 0
save-interval-epochs: 10
eval-interval-epochs: 10
report-interval-iters: 100
pretrained-tts-model: downloads/snapshot.ep.290
