embed-dim: 512
elayers: 1
eunits: 512
econv-layers: 3
econv-chans: 512
econv-filts: 5
dlayers: 2
dunits: 1024
prenet-layers: 2
prenet-units: 256
postnet-layers: 5
postnet-chans: 512
postnet-filts: 5
use-speaker-embedding: true
atype: location
adim: 128
aconv-chans: 32
aconv-filts: 15
cumulate-att-w: true
use-batch-norm: true
use-concate: true
use-residual: false
use-masking: true
bce-pos-weight: 1.0
use-guided-attn-loss: true
guided-attn-loss-sigma: 0.4
reduction-factor: 2
batch-sort-key: input
batch-bins: 2428800
lr: 1e-4
eps: 1e-6
weight-decay: 0.0
dropout-rate: 0.5
zoneout-rate: 0.1
epochs: 200
patience: 0
save-interval-epoch: 10
pretrained-model: downloads/CH_TG.tacotron2+spkemb/exp/train_pytorch_train_pytorch_tacotron2+spkemb/results/model.last1.avg.best
